### ISSUE TITLE
DrSeussBot.py Refers to Removed ChatterBot Class

### ISSUE THREAD

**Issue by JeffreyMitchellSL** [gregbmeyer/Chatbotwithfeedback#1]
At line 17, DrSeussBot.py passes `'chatterbot.logic.LowConfidenceAdapter'` to the `ChatBot` constructor, which throws an exception.

`LowConfidenceAdapter` no longer exists in the ChatterBot repository:
https://github.com/gunthercox/ChatterBot/issues/1644#issuecomment-468087642

**Comment by gregbmeyer** [comment]
Code is updated with the equivalent new logic adapter:  BestMatch.
Thanks for the catch!!
